---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, gfc, global file cache' 
summary: BlueXP 에지 캐싱의 새로운 기능에 대해 알아보십시오. 
---
= BlueXP 에지 캐싱의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 에지 캐싱의 새로운 기능에 대해 알아보십시오.



== 2024년 5월 31일

NetApp은 2024년 5월 31일 부로 NetApp Global File Cache의 공급 중지(EOA)를 발표했습니다. EOA는 독립 실행형 Global File Cache 소프트웨어 구독 및 NetApp Cloud Volumes Edge Cache라고 하는 NetApp Cloud Volumes ONTAP와 Global File Cache 번들 솔루션을 포함한 모든 NetApp Global File Cache 제품에 영향을 미칩니다.

NetApp은 기존 고객을 위해 최소 3년 동안 이러한 제품을 계속 지원할 것입니다. https://mysupport.netapp.com/info/communications/CPC-00578.html["NetApp Global File Cache의 공급 중지 세부 정보를 참조하십시오"^].

또한 BlueXP 사용자 인터페이스에서 Global File Cache 구성요소를 사용, 구축 및 관리하는 기능이 제거되었습니다.



== 2024년 5월 6일(버전 2.4)

이 릴리스는 일부 사소한 문제를 해결합니다. 업데이트된 소프트웨어 패키지는 에서 확인할 수 있습니다 https://docs.netapp.com/us-en/bluexp-edge-caching/download-gfc-resources.html#download-required-resources["이 페이지"].



== 2023년 8월 1일(버전 2.3)

이 릴리스는 에 설명된 문제를 해결합니다 https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["해결된 문제"]. 업데이트된 소프트웨어 패키지는 에서 확인할 수 있습니다 https://docs.netapp.com/us-en/bluexp-edge-caching/download-gfc-resources.html#download-required-resources["이 페이지"].



== 2023년 4월 5일(버전 2.2)

이 릴리스는 아래 나열된 새 기능을 제공합니다. 또한 에 설명된 문제도 해결합니다 https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["해결된 문제"].



=== Google Cloud에 구축된 Cloud Volumes ONTAP 시스템에서 글로벌 파일 캐시 지원

Google Cloud에서 Cloud Volumes ONTAP 시스템을 구축할 때 새로운 "Edge Cache" 라이센스가 제공됩니다. 구매한 각 3TiB의 Cloud Volumes ONTAP 시스템에도 하나의 글로벌 파일 캐시 에지 시스템을 구축할 수 있습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#packages["Edge Cache 라이센스 패키지에 대해 자세히 알아보십시오."]



=== 설정 마법사와 GFC 구성 UI는 NetApp 라이센스 등록을 수행할 수 있도록 향상되었습니다



=== Edge Sync 기능을 구성하기 위한 Enhanced Optimus PSM



== 2022년 10월 24일(버전 2.1)

이 릴리스는 아래 나열된 새 기능을 제공합니다. 또한 에 설명된 문제도 해결합니다 https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["해결된 문제"].



=== 이제 글로벌 파일 캐시를 원하는 수의 라이센스로 사용할 수 있습니다

이전에 최소 10개의 라이센스 또는 30TB의 스토리지가 제거되었습니다. 3TB의 스토리지당 하나의 글로벌 파일 캐시 라이센스가 발급됩니다.



=== 오프라인 License Management Server 사용에 대한 지원이 추가되었습니다

오프라인 또는 다크 사이트 LMS(License Management Server)는 LMS가 라이선스 소스를 통한 라이선스 검증을 위한 인터넷 연결이 없는 경우에 가장 유용합니다. 초기 구성 중에 인터넷 연결 및 라이센스 소스 연결이 필요합니다. 구성한 후에는 LMS 인스턴스가 어두워질 수 있습니다. 모든 엣지/코어는 라이센스의 지속적인 검증을 위해 LMS와 연결되어 있어야 합니다.



=== Edge 인스턴스는 추가 동시 사용자를 지원할 수 있습니다

단일 Global File Cache Edge 인스턴스는 전용 물리적 Edge 인스턴스당 최대 500명의 사용자와 최대 300명의 전용 가상 구축 사용자를 지원할 수 있습니다. 최대 사용자 수는 400명, 200명입니다.



=== 클라우드 라이센스를 구성하기 위한 Optimus PSM이 개선되었습니다



=== Optimus UI(Edge Configuration)의 Edge Sync 기능이 향상되어 연결된 모든 클라이언트가 표시됩니다



== 2022년 7월 25일(버전 2.0)

이 릴리스는 아래 나열된 새 기능을 제공합니다. 또한 에 설명된 문제도 해결합니다 https://docs.netapp.com/us-en/bluexp-edge-caching/fixed-issues.html["해결된 문제"].



=== Azure 마켓플레이스를 통해 글로벌 파일 캐시에 대한 새로운 용량 기반 라이센스 모델을 제공합니다

새로운 "Edge Cache" 라이센스는 "CVO Professional" 라이센스와 동일한 기능을 제공하지만 Global File Cache도 지원합니다. Azure에서 새 Cloud Volumes ONTAP 시스템을 구축할 때 이 옵션이 표시됩니다. Cloud Volumes ONTAP 시스템에서 3TiB의 프로비저닝된 각 용량에 대해 하나의 글로벌 파일 캐시 에지 시스템을 구축할 수 있습니다. 최소 30TiB를 프로비저닝해야 합니다. GFC License Manager Service는 용량 기반 라이센스를 제공하도록 개선되었습니다.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["Edge Cache 라이센스 패키지에 대해 자세히 알아보십시오."]



=== 이제 글로벌 파일 캐시가 Cloud Insights와 통합되었습니다

NetApp CI(Cloud Insights)를 사용하면 인프라 및 애플리케이션을 완벽하게 파악할 수 있습니다. 이제 글로벌 파일 캐시가 CI와 통합되어 모든 에지 및 코어를 완벽하게 파악할 수 있으며 인스턴스에서 실행 중인 프로세스를 모니터링할 수 있습니다. CI 대시보드에서 전체 개요를 제공하기 위해 다양한 글로벌 파일 캐시 메트릭이 CI로 푸시됩니다. 의 11장을 참조하십시오 https://repo.cloudsync.netapp.com/gfc/Global%20File%20Cache%202.1.0%20User%20Guide.pdf["NetApp 글로벌 파일 캐시 사용자 가이드 를 참조하십시오"^]

https://cloud.netapp.com/cloud-insights["Cloud Insights에 대해 자세히 알아보십시오."]



=== License Management Server는 매우 제한적인 환경에서 작동하도록 향상되었습니다

라이센스 구성 중에 LMS(License Management Server)에서 NetApp/Zuora로부터 라이센스 세부 정보를 수집하기 위해 인터넷에 액세스할 수 있어야 합니다. 구성이 성공적으로 완료되면 LMS는 제한된 환경에도 불구하고 오프라인 모드에서 계속 작업하고 라이선스 기능을 제공할 수 있습니다.



=== Optimus의 Edge Sync UI는 코디네이터 Edge에 연결된 클라이언트 목록을 표시하도록 향상되었습니다
